name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run gofmt
      run: |
        OUTPUT=`gofmt -d .`; if [ -n "$OUTPUT" ]; then echo "$OUTPUT"; exit 1; fi

    - name: Build Examples
      run: |
        for i in ./_examples/*.go; do go build -v "$i"; done

    - name: Install deltachat-rpc-server
      run: |
        rustup toolchain install 1.64.0
        rustup override set 1.64.0
        cargo install --git https://github.com/deltachat/deltachat-core-rust/ deltachat-rpc-server

    - name: Test
      run: go test -v ./...
